In [2]:
%load_ext autoreload
%autoreload 2

import sys
import torch
sys.path.insert(1, '../')
import src

from src.utils.init_utils import seed_all, set_gpu_device, load_dataset, load_split
seed_all()
gpu_number=3
device, run_on_gpu = set_gpu_device(gpu_number)

Global seed set to 5


Number of cuda devices: 0
My device: cpu


## Preparing Dataset

In [13]:
val_ds = load_split('validation', use_SC=True, use_coef=True)

In [18]:
print(val_ds.params[10])

tensor([ 7.0197e+00, -1.5222e+00,  4.0103e-01,  2.5643e+00,  3.5237e-01,
         7.1930e-02,  1.7195e-03,  2.2451e-03,  7.2764e-05,  2.0611e+00])


In [19]:
test_ds = load_split('test', use_SC=True, use_coef=True)

SC loaded for test 1!
10000 param coefficients loaded for test 1!
SC loaded for test 2!
10000 param coefficients loaded for test 2!
SC loaded for test 3!
10000 param coefficients loaded for test 3!
SC loaded for test 4!
10000 param coefficients loaded for test 4!
SC loaded for test 5!
10000 param coefficients loaded for test 5!
SC loaded for test 6!
10000 param coefficients loaded for test 6!
SC loaded for test 7!
10000 param coefficients loaded for test 7!
SC loaded for test 8!
10000 param coefficients loaded for test 8!
SC loaded for test 9!
10000 param coefficients loaded for test 9!
SC loaded for test 10!
10000 param coefficients loaded for test 10!
SC loaded for test 11!
10000 param coefficients loaded for test 11!
SC loaded for test 12!
10000 param coefficients loaded for test 12!
SC loaded for test 13!
10000 param coefficients loaded for test 13!
SC loaded for test 14!
10000 param coefficients loaded for test 14!
SC loaded for test 15!
10000 param coefficients loaded for test 15

In [20]:
train_ds = load_split('train', use_SC=True, use_coef=True)

SC loaded for train 1!
10000 param coefficients loaded for train 1!
SC loaded for train 2!
10000 param coefficients loaded for train 2!
SC loaded for train 3!
10000 param coefficients loaded for train 3!
SC loaded for train 4!
10000 param coefficients loaded for train 4!
SC loaded for train 5!
10000 param coefficients loaded for train 5!
SC loaded for train 6!
10000 param coefficients loaded for train 6!
SC loaded for train 7!
10000 param coefficients loaded for train 7!
SC loaded for train 8!
10000 param coefficients loaded for train 8!
SC loaded for train 9!
10000 param coefficients loaded for train 9!
SC loaded for train 10!
10000 param coefficients loaded for train 10!
SC loaded for train 11!
10000 param coefficients loaded for train 11!
SC loaded for train 12!
10000 param coefficients loaded for train 12!
SC loaded for train 13!
10000 param coefficients loaded for train 13!
SC loaded for train 14!
10000 param coefficients loaded for train 14!
SC loaded for train 15!
10000 param co

In [21]:
train_ds, validation_ds, test_ds = load_dataset(use_SC=True, use_coef=True)

In [2]:
train_ds, validation_ds, test_ds = load_dataset()

SC loaded for train 1!
10000 params loaded for train 1!
SC loaded for train 2!
10000 params loaded for train 2!
SC loaded for train 3!
10000 params loaded for train 3!
SC loaded for train 4!
10000 params loaded for train 4!
SC loaded for train 5!
10000 params loaded for train 5!
SC loaded for train 6!
10000 params loaded for train 6!
SC loaded for train 7!
10000 params loaded for train 7!
SC loaded for train 8!
10000 params loaded for train 8!
SC loaded for train 9!
10000 params loaded for train 9!
SC loaded for train 10!
10000 params loaded for train 10!
SC loaded for train 11!
10000 params loaded for train 11!
SC loaded for train 12!
10000 params loaded for train 12!
SC loaded for train 13!
10000 params loaded for train 13!
SC loaded for train 14!
10000 params loaded for train 14!
SC loaded for train 15!
10000 params loaded for train 15!
SC loaded for train 16!
10000 params loaded for train 16!
SC loaded for train 17!
10000 params loaded for train 17!
SC loaded for train 18!
10000 pa

In [14]:
train_ds.cost_vectors[10:20]

[tensor([1., 1., 1.]),
 tensor([1., 1., 1.]),
 tensor([1., 1., 1.]),
 tensor([1., 1., 1.]),
 tensor([0.5190, 0.0437, 0.8637]),
 tensor([1., 1., 1.]),
 tensor([1., 1., 1.]),
 tensor([1., 1., 1.]),
 tensor([1., 1., 1.]),
 tensor([1., 1., 1.])]

In [8]:
train_ds_no_SC, validation_ds_no_SC, test_ds_no_SC = load_dataset(use_SC=False)

SC loaded for train 1!
10000 params loaded for train 1!
SC loaded for train 2!
10000 params loaded for train 2!
SC loaded for train 3!
10000 params loaded for train 3!
SC loaded for train 4!
10000 params loaded for train 4!
SC loaded for train 5!
10000 params loaded for train 5!
SC loaded for train 6!
10000 params loaded for train 6!
SC loaded for train 7!
10000 params loaded for train 7!
SC loaded for train 8!
10000 params loaded for train 8!
SC loaded for train 9!
10000 params loaded for train 9!
SC loaded for train 10!
10000 params loaded for train 10!
SC loaded for train 11!
10000 params loaded for train 11!
SC loaded for train 12!
10000 params loaded for train 12!
SC loaded for train 13!
10000 params loaded for train 13!
SC loaded for train 14!
10000 params loaded for train 14!
SC loaded for train 15!
10000 params loaded for train 15!
SC loaded for train 16!
10000 params loaded for train 16!
SC loaded for train 17!
10000 params loaded for train 17!
SC loaded for train 18!
10000 pa

In [9]:
from src.models.gnn.gnn_param_dataset import GnnParamDataset
gnn_train_ds, gnn_validation_ds, gnn_test_ds = GnnParamDataset('train'), GnnParamDataset('validation'), GnnParamDataset('test')

Processing...


SC loaded for train 1!
10000 params loaded for train 1!
SC loaded for train 2!
10000 params loaded for train 2!
SC loaded for train 3!
10000 params loaded for train 3!
SC loaded for train 4!
10000 params loaded for train 4!
SC loaded for train 5!
10000 params loaded for train 5!
SC loaded for train 6!
10000 params loaded for train 6!
SC loaded for train 7!
10000 params loaded for train 7!
SC loaded for train 8!
10000 params loaded for train 8!
SC loaded for train 9!
10000 params loaded for train 9!
SC loaded for train 10!
10000 params loaded for train 10!
SC loaded for train 11!
10000 params loaded for train 11!
SC loaded for train 12!
10000 params loaded for train 12!
SC loaded for train 13!
10000 params loaded for train 13!
SC loaded for train 14!
10000 params loaded for train 14!
SC loaded for train 15!
10000 params loaded for train 15!
SC loaded for train 16!
10000 params loaded for train 16!
SC loaded for train 17!
10000 params loaded for train 17!
SC loaded for train 18!
10000 pa

Done!


In [16]:
gnn_train_ds[0].y

tensor([[1., 1., 1.]])

In [4]:
len(gnn_validation_ds.data)

4

In [10]:
gnn_validation_ds._data_list

None


## Training

In [25]:
from src.models.naive_net import objective_naive_net_no_SC_use_coef
from src.utils.training_utils import tune
tune(objective_naive_net_no_SC_use_coef, train_ds=train_ds, validation_ds=validation_ds, n_trials=5, timeout=600, save_dir='./tmp/')
# tune(objective_naive_net_no_SC_use_coef, n_trials=5, timeout=600, save_dir='./tmp/', use_coef=True)

[I 2022-08-07 00:42:05,443] A new study created in memory with name: no-name-88fbba1b-c2d8-45b3-bc0f-87a87efdb070
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name      | Type       | Params
-----------------------------------------
0 | loss_fn   | MSELoss    | 0     
1 | criterion | MSELoss    | 0     
2 | layers    | Sequential | 6.0 K 
-----------------------------------------
6.0 K     Trainable params
0         Non-trainable params
6.0 K     Total params
0.024     Total estimated model params size (MB)
/home/ftian/storage/miniconda/envs/pMFM_speedup-torch1.8/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `Data

Number of finished trials: 5
Best trial:
  Trial number: 3
  Value: 0.3106759190559387
  Params: 
    num_of_naive_net_layers: 5
    naive_net_output_dim_l0: 7
    naive_net_output_dim_l1: 153
    naive_net_output_dim_l2: 11
    naive_net_output_dim_l3: 21
    naive_net_output_dim_l4: 12


In [ ]:
from src.models.naive_net import objective_naive_net_no_SC
from src.utils.training_utils import tune
tune(objective_naive_net_no_SC, train_ds=train_ds, validation_ds=validation_ds, n_trials=5, timeout=600, save_dir='./tmp/')

In [ ]:
from src.models.naive_net import objective_naive_net_with_SC
tune(objective_naive_net_with_SC, train_ds=train_ds, validation_ds=validation_ds, n_trials=5, timeout=600, save_dir='./tmp/')


In [ ]:
from src.utils.training_utils import tune_gnn
from src.models.gnn.gcn import objective_gcn
tune_gnn(objective_gcn, train_ds=gnn_train_ds, validation_ds=gnn_validation_ds, n_trials=5, timeout=3600, save_dir='./tmp/')


## Testing

In [7]:
test_ds = load_split('test', use_SC=False, use_coef=False)

test dataset loaded!


In [10]:
from src.testing.testing_lib import load_naive_net_no_SC
model = load_naive_net_no_SC()

In [18]:
from src.utils.test_utils import test_model
test_model(model, test_ds)

torch.Size([170000, 3])
torch.Size([170000, 3])
MSE loss: 0.024801483377814293


## Debugging

In [14]:
BATCH_SIZE = 256
NUM_WORKERS = 0
PIN_MEMORY = True

# Create data loaders for our datasets; shuffle for training, not for validation
training_loader = torch.utils.data.DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, \
                                                num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)
validation_loader = torch.utils.data.DataLoader(validation_ds, batch_size=BATCH_SIZE, shuffle=False, \
                                                num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)

In [ ]:
from src.models.naive_net import NaiveNet

naive_net = NaiveNet(use_SC_feat=False, output_dims=[5])
print(naive_net)


In [15]:
dataiter = iter(training_loader)
(SCs, params), labels = dataiter.next()

SCs = SCs.to(device=device, non_blocking=True)
params = params.to(device=device, non_blocking=True)
print(SCs.is_cuda)

False


In [24]:
print(labels.shape)

torch.Size([256, 4])


In [20]:
sample_output = naive_net((SCs, params))
print(sample_output.shape)

torch.Size([256, 205])
torch.Size([256, 3])


In [1]:
import optuna
import pickle
study = pickle.load(open('/home/ftian/storage/pMFM_speedup/reports/training_log/basic_models/naive_net/with_SC/study.pkl', 'rb'))

In [2]:
import optuna
import pickle
study = pickle.load(open('/home/ftian/storage/pMFM_speedup/reports/training_log/basic_models/naive_net/no_SC/study.pkl', 'rb'))

In [4]:
import optuna
import pickle
study = pickle.load(open('/home/ftian/storage/pMFM_speedup/reports/training_log/gnn/gcn_with_mlp/study.pkl', 'rb'))

In [5]:
study.best_trial.number

37

In [ ]:
from src.utils.SC_utils import show_corr_between_all_SCs
show_corr_between_all_SCs()

In [6]:
from src.basic.subject_group import SubjectGroup
